export interface Horse {
    id: number,
    horse_name: string,
    trainer: string,
    regular_jockey: string,
    owner: string,
    age: string,
    gender: string,
    sire: string,
    form: string,
    races: string,
    wins: string,
    places: string,
    win_percentage: string,
    place_percentage: string,
    type: string,
    distance: string,
    ground: string,
    track: string,
    comments: string,
    link: string
  }